<a href="https://colab.research.google.com/github/DevP-ai/Machine-Learning/blob/master/PPG_BP_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [79]:
df=pd.read_csv("/content/PPG-BP dataset  0111.csv")

In [80]:
df.sample(5)

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
80     81         115   Female         54         150          82   
206   207         406   Female         26         171          75   
63     64          95   Female         64         163          72   
77     78         112     Male         61         165          66   
201   202         257   Female         28         160          58   

     Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
80                             108                              66   
206                            106                              63   
63                             153                              71   
77                             173                             100   
201                            122                              70   

     Heart Rate(b/m)  BMI(kg/m^2)          Hypertension  
80                62        36.44                     0  
206               69        25.65                     0  
63                59        27.10  Stage 1 hypertension  
77                89        24.24                    11  
201               88        22.66                     1

In [81]:
df['Hypertension'].replace({'Normal':'00'},inplace=True)
df['Hypertension'].replace({'Prehypertension':'01'},inplace=True)
df['Hypertension'].replace({'Stage 1 hypertension':'10'},inplace=True)
df['Hypertension'].replace({'Stage 2 hypertension':'11'},inplace=True)

In [82]:
df.sample(10)

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
51     52          67   Female         42         152          49   
111   112         154   Female         84         162          80   
169   170         220   Female         55         155          50   
74     75         108     Male         58         160          65   
185   186         239     Male         53         175          75   
123   124         167   Female         57         157          44   
215   216         416   Female         25         156          47   
199   200         254   Female         64         150          47   
94     95         135     Male         56         165          70   
75     76         110     Male         60         154          50   

     Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
51                             100                              63   
111                            149                              70   
169                            174                             104   
74                             137                              65   
185                            138                              93   
123                            107                              60   
215                             93                              57   
199                            124                              70   
94                             165                              86   
75                             120                              63   

     Heart Rate(b/m)  BMI(kg/m^2) Hypertension  
51                67        21.21            0  
111               69        30.48           10  
169               96        20.81           11  
74                72        25.39            1  
185               65        24.49            1  
123               67        17.85            0  
215               79        19.31            0  
199               77        20.89            1  
94                73        25.71           11  
75                86        21.08            1

In [76]:
# one_hot_encoded_data = pd.get_dummies(df,columns = ['Hypertension'])
# one_hot_encoded_data

Num.  subject_ID Sex(M/F)  Age(year)  Height(cm)  Weight(kg)  \
0       1           2   Female         45         152          63   
1       2           3   Female         50         157          50   
2       3           6   Female         47         150          47   
3       4           8     Male         45         172          65   
4       5           9   Female         46         155          65   
..    ...         ...      ...        ...         ...         ...   
214   215         415     Male         24         180          70   
215   216         416   Female         25         156          47   
216   217         417     Male         25         176          55   
217   218         418     Male         25         173          63   
218   219         419     Male         24         175          58   

     Systolic Blood Pressure(mmHg)  Diastolic Blood Pressure(mmHg)  \
0                              161                              89   
1                              160                              93   
2                              101                              71   
3                              136                              93   
4                              123                              73   
..                             ...                             ...   
214                            111                              70   
215                             93                              57   
216                            120                              69   
217                            106                              69   
218                            108                              68   

     Heart Rate(b/m)  BMI(kg/m^2) Diabetes cerebral infarction  \
0                 97        27.27      NaN                 NaN   
1                 76        20.28      NaN                 NaN   
2                 79        20.89      NaN                 NaN   
3                 87        21.97      NaN                 NaN   
4                 73        27.06      NaN                 NaN   
..               ...          ...      ...                 ...   
214               77        21.60      NaN                 NaN   
215               79        19.31      NaN                 NaN   
216               72        17.76      NaN                 NaN   
217               67        21.05      NaN                 NaN   
218               65        18.94      NaN                 NaN   

    cerebrovascular disease  Hypertension_Normal  \
0                       NaN                    0   
1                       NaN                    0   
2                       NaN                    1   
3                       NaN                    0   
4                       NaN                    0   
..                      ...                  ...   
214                     NaN                    1   
215                     NaN                    1   
216                     NaN                    0   
217                     NaN                    1   
218                     NaN                    1   

     Hypertension_Prehypertension  Hypertension_Stage 1 hypertension  \
0                               0                                  0   
1                               0                                  0   
2                               0                                  0   
3                               1                                  0   
4                               1                                  0   
..                            ...                                ...   
214                             0                                  0   
215                             0                                  0   
216                             1                                  0   
217                             0                                  0   
218                             0                                  0   

     Hypertension_Stage 2 hypertension  
0          

In [95]:
feature=["BMI(kg/m^2)","Heart Rate(b/m)","Diastolic Blood Pressure(mmHg)","Height(cm)","Weight(kg)","Systolic Blood Pressure(mmHg)"]

In [96]:
X=df[feature].values

In [97]:
y=df["Hypertension"].values

In [98]:
X

array([[ 27.27,  97.  ,  89.  , 152.  ,  63.  , 161.  ],
       [ 20.28,  76.  ,  93.  , 157.  ,  50.  , 160.  ],
       [ 20.89,  79.  ,  71.  , 150.  ,  47.  , 101.  ],
       ...,
       [ 17.76,  72.  ,  69.  , 176.  ,  55.  , 120.  ],
       [ 21.05,  67.  ,  69.  , 173.  ,  63.  , 106.  ],
       [ 18.94,  65.  ,  68.  , 175.  ,  58.  , 108.  ]])

In [99]:
X.shape

(219, 6)

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [101]:
from sklearn.preprocessing import StandardScaler

In [102]:
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(X_train) 
xtest = sc_x.transform(X_test)

In [103]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, y_train)

LogisticRegression(random_state=0)

In [104]:
y_pred = classifier.predict(xtest)

In [105]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[16  0  0  0]
 [ 2 25  1  0]
 [ 0  1  8  0]
 [ 0  0  0  2]]


In [106]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9272727272727272


In [107]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred, average='macro') 

(0.9348290598290598, 0.9454365079365079, 0.9389978213507625, None)

In [50]:
precision_recall_fscore_support(y_test, y_pred, average='weighted')


(0.5509090909090909, 0.5636363636363636, 0.5523232323232323, None)